# Solved by me

### Package Imports

In [1]:
import numpy as np

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [6]:
my_list = [x * 10 for x in range(1, 11)]

my_list = np.array(my_list)

print(my_list)

[ 10  20  30  40  50  60  70  80  90 100]


In [8]:
print(f"number of dimension: {my_list.ndim}")
print(f"shape: {my_list.shape}")
print(f"number of element: {my_list.size}")
print(f"type of data: {my_list.dtype}")

number of dimension: 1
shape: (10,)
number of element: 10
type of data: int32


# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [4]:
my_array = np.linspace(10,100,10).reshape(5,2)
my_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [6]:
rng = np.random.default_rng(2022)
random_array = rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.

Thanks!


In [13]:
random_array[:2]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [29]:
random_array[:,0]

array([0.24742606, 0.06066207, 0.1108689 ])

In [31]:
random_array[2,1]

0.04305584439252108

# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [3]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])


In [36]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [45]:
discount_pct = random_array[:2].reshape(6)
pct_owed = 1 - discount_pct

final_amount = pct_owed * total

In [47]:
final_amount.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [2]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [6]:
products[prices > 25]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [13]:
mask = (prices>25) | (products == 'cola')

fancy_feast_special = mask

fancy_feast_special = products[mask]

fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [14]:
shipping_cost = np.where(prices>20,0,5)

shipping_cost

array([5, 5, 0, 0, 5, 0])

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [27]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [39]:
top_3 = np.sort(prices)[-3:]

In [41]:
print(f"mean: {top_3.mean()}")
print(f"min: {top_3.min()}")
print(f"max: {top_3.max()}")
print(f"median: {np.median(top_3)}")

mean: 57.49
min: 22.49
max: 99.99
median: 49.99


In [42]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [46]:
np.unique(price_tiers)

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

### Thank you 